import { StyleSheet } from 'react-native';

export const getBudgetStyles = (colors) => StyleSheet.create({
    // Main screen styles
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: colors.text,
        marginBottom: 20,
        textAlign: 'center',
    },
    itemContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 15,
        backgroundColor: colors.card,
        borderRadius: 12,
        marginBottom: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    itemDetails: {
        flex: 1,
    },
    itemText: {
        fontSize: 18,
        fontWeight: '600',
        color: colors.text,
    },
    itemSubText: {
        fontSize: 14,
        color: colors.secondaryText,
        marginTop: 4,
    },
    itemAmountContainer: {
        alignItems: 'flex-end',
    },
    itemAmount: {
        fontSize: 18,
        fontWeight: 'bold',
    },
    itemActions: {
        flexDirection: 'row',
        marginTop: 8,
    },
    editButton: {
        marginRight: 15,
    },
    deleteButton: {},
    summaryCard: {
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 20,
        marginTop: 20,
        marginHorizontal: 20, // Added horizontal margin
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    summaryTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: colors.text,
        marginBottom: 15,
    },
    summaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    summaryLabel: {
        fontSize: 16,
        color: colors.secondaryText,
    },
    summaryAmount: {
        fontSize: 16,
        fontWeight: 'bold',
    },
    fab: {
        position: 'absolute',
        margin: 16,
        right: 0,
        bottom: 0,
        backgroundColor: colors.primary,
    },

    // MODAL AND FORM STYLES
    modalBackdrop: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    formContainer: {
        backgroundColor: colors.background,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingHorizontal: 20,
        paddingTop: 10,
        paddingBottom: 30, 
        maxHeight: '90%',
    },
    handleBar: {
        width: 40,
        height: 5,
        backgroundColor: colors.border,
        borderRadius: 3,
        alignSelf: 'center',
        marginBottom: 10,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingBottom: 15,
        marginBottom: 10,
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: colors.text,
    },
    formGroup: {
        marginBottom: 15,
    },
    label: {
        fontSize: 16,
        color: colors.secondaryText,
        marginBottom: 10,
        fontWeight: '500',
    },
    toggleContainer: {
        flexDirection: 'row',
        marginBottom: 15,
        backgroundColor: colors.input,
        borderRadius: 12,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: colors.border,
    },
    toggleButton: {
        flex: 1,
        padding: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    activeToggleButton: {
        backgroundColor: colors.primary,
    },
    toggleButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
    },
    activeToggleButtonText: {
        color: '#FFFFFF',
    },
    input: {
        backgroundColor: colors.input,
        borderRadius: 10,
        padding: 15,
        fontSize: 16,
        color: colors.text,
        borderWidth: 1,
        borderColor: colors.border,
    },
    amountContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    periodSelectorButton: {
        padding: 15,
        marginLeft: 10,
        backgroundColor: colors.input,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.border,
    },
    periodOptionsContainer: {
        backgroundColor: colors.card,
        borderRadius: 8,
        padding: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        marginTop: 10,
    },
    periodOption: {
        padding: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    periodOptionText: {
        fontSize: 16,
        color: colors.text,
    },
    periodApproximationText: {
        fontSize: 12,
        color: colors.secondaryText,
    },
    categoryContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        marginBottom: 15,
        gap: 10,
    },
    categoryButton: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 10,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: colors.border,
        width: '30%',
        height: 85,
        backgroundColor: colors.input,
    },
    activeCategory: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    categoryIcon: {
        marginBottom: 8,
    },
    categoryText: {
        fontSize: 12,
        color: colors.text,
        fontWeight: '600',
        textAlign: 'center',
    },
    activeCategoryText: {
        color: '#FFFFFF',
    },
    deductContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 15,
        backgroundColor: colors.input,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.border,
    },
    deductLabel: {
        fontSize: 16,
        color: colors.text,
        fontWeight: '500',
    },
    reminderContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 15,
        backgroundColor: colors.input,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.border,
    },
    reminderLabel: {
        fontSize: 16,
        color: colors.text,
        fontWeight: '500',
    },
    datePickerButton: {
        backgroundColor: colors.input,
        borderRadius: 10,
        padding: 15,
        alignItems: 'center',
        marginTop: 10,
        borderWidth: 1,
        borderColor: colors.border,
    },
    datePickerButtonText: {
        fontSize: 16,
        color: colors.text,
        fontWeight: '500',
    },
    button: {
        padding: 18,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 10,
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
});