import { StyleSheet } from 'react-native';
import { Colors } from '../constants/Colors';

type IColors = typeof Colors.light;

export const getReportsStyles = (colors: IColors) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
        padding: 16,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        marginTop: 50,
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: colors.text,
    },
    exportButton: {
        padding: 8,
        borderRadius: 8,
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border,
    },
    filterContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: 20,
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 4,
    },
    filterButton: {
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
        backgroundColor: 'transparent',
        flex: 1,
        alignItems: 'center',
    },
    activeFilterButton: {
        backgroundColor: colors.primary,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    filterButtonText: {
        fontSize: 14,
        color: colors.text,
        fontWeight: '600',
    },
    activeFilterButtonText: {
        color: '#FFFFFF',
        fontWeight: '700',
    },
    chartTypeContainer: {
        marginBottom: 20,
    },
    chartTypeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 16,
        marginRight: 12,
        borderRadius: 20,
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border,
    },
    activeChartTypeButton: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    chartTypeButtonText: {
        fontSize: 14,
        color: colors.text,
        fontWeight: '600',
        marginLeft: 6,
    },
    activeChartTypeButtonText: {
        color: colors.background,
        fontWeight: '700',
    },
    chartContainer: {
        marginBottom: 30,
        backgroundColor: colors.card,
        borderRadius: 16,
        padding: 20,
        alignItems: 'center',
        shadowColor: colors.text,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    chartHeader: {
        width: '100%',
        marginBottom: 20,
    },
    chartTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: colors.text,
        marginBottom: 15,
        textAlign: 'center',
    },
    chart: {
        borderRadius: 16,
    },
    analyticsRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginTop: 10,
    },
    analyticsItem: {
        alignItems: 'center',
        flex: 1,
    },
    analyticsLabel: {
        fontSize: 12,
        color: colors.secondaryText,
        marginBottom: 4,
        textTransform: 'uppercase',
        fontWeight: '600',
    },
    analyticsValue: {
        fontSize: 18,
        fontWeight: '700',
        marginBottom: 2,
    },
    analyticsChange: {
        fontSize: 12,
        fontWeight: '600',
    },
    progressStats: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        marginBottom: 20,
    },
    progressStat: {
        alignItems: 'center',
        flex: 1,
    },
    progressLabel: {
        fontSize: 14,
        color: colors.secondaryText,
        marginBottom: 8,
        fontWeight: '600',
    },
    progressValue: {
        fontSize: 24,
        fontWeight: '700',
    },
    summaryContainer: {
        backgroundColor: colors.card,
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        shadowColor: colors.text,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    summaryTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: colors.text,
        marginBottom: 20,
        textAlign: 'center',
    },
    insightGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    insightCard: {
        width: '48%',
        backgroundColor: colors.background,
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
    },
    insightLabel: {
        fontSize: 12,
        color: colors.secondaryText,
        marginTop: 8,
        marginBottom: 4,
        textAlign: 'center',
        fontWeight: '600',
    },
    insightValue: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.text,
        textAlign: 'center',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.background,
    },
    loadingText: {
        fontSize: 16,
        color: colors.secondaryText,
        marginTop: 16,
        textAlign: 'center',
    },
    errorText: {
        fontSize: 16,
        color: colors.danger,
        textAlign: 'center',
        marginTop: 20,
        padding: 20,
        backgroundColor: colors.card,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.danger,
    },
    emptyStateText: {
        fontSize: 16,
        color: colors.secondaryText,
        textAlign: 'center',
        marginTop: 20,
        fontStyle: 'italic',
    },
}); 